[platformio]
src_dir = .

[env:esp32s3]
platform  = espressif32
board     = esp32s3box
framework = arduino

monitor_speed = 115200

lib_deps =
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson  @ ^7.2
  https://github.com/espressif/esp32-camera

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DBOARD_HAS_PSRAM              ; Enable PSRAM support for JPEG frame buffer
  -DMQTT_MAX_PACKET_SIZE=51200   ; 50 KB — large enough for a 320x240 JPEG in Base64

board_build.arduino.partitions = huge_app.csv   ; Needed for larger app + camera driver
